import { Roboto, PT_Sans, Kodchasan, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import WhatsappButton from "@/components/shared/WhatsappButton";
import Footer from "@/components/layout/Footer";

// Primary Font: Roboto - Weights: 300, 400, 500, 900
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "900"],
});

// Secondary Font: PT Sans
const ptSans = PT_Sans({
  variable: "--font-pt-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

// Accent Font: Kodchasan
const kodchasan = Kodchasan({
  variable: "--font-kodchasan",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

// Display Font: Montserrat - Weight: 700
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["700"],
});

export const metadata = {
  title: "Yourself Pilates - Pilates studio in Caldas da Rainha",
  description: "Generated by create next app",
  icons: {
    icon: "/images/HeaderIcon.png",
  },
};

import { Toaster } from "@/components/ui/sonner";

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.variable} ${ptSans.variable} ${kodchasan.variable} ${montserrat.variable} antialiased`}
        suppressHydrationWarning
      >
        {/* Header Component */}
        <Header />

        {/* WhatsApp Floating Button */}
        <WhatsappButton />
        {children}

        {/* Footer Component */}
        <Footer />
      </body>
    </html>
  );
}
